### ISSUE TITLE
Common step length class

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl-solvers#5]
I suggest that we write a common class for step length calculation which tells the algorithm what it needs (which part of the history), such that an algorithm can determine which iterates and gradients (what else?) to keep.

A simple approach would be to give the `StepLength` class attributes

- `iter_idcs` (iterates)
- `func_idcs` (function evaluations)
- `grad_idcs` (gradient evaluations / approximations)
- `hess_idcs` (Hessian evaluations / approximations)
- `step_idcs` (step lengths)

which all return lists of indices of items to keep. An algorithm could manage lists of all these objects and pass its lists (possibly kept in a dictionary) to the step length call, which in turn does its thing to calculate the step length.

**Comment by aringh** [comment]
Right now the interface looks like
`class LineSearch(object):`

    """Base class for line search methods to calculate step lenghts. """

    def __call__(self, x, direction, gradf):

I'm not sure I understand what you mean with lists of indices; what happens if my problem does not have a Hessian? Can I pass `None` (or similar)?

**Comment by kohr-h** [comment]
Yes, something like that. The `StepLength` class could return `None` or, better, an empty list if it does not need anything of a specific kind, e.g. Hessian. In that case, the method would not store a Hessian. One could even check beforehand if the step length rule is applicable in the first place. For example, if you need an explicit gradient for a step length, but the optimization scheme does not compute it, an error could be thrown.

I'll know more once I have some code before me. First goal is to support what we have, of course.

**Comment by adler-j** [comment]
Moved to https://github.com/odlgroup/odl/issues/50
