### ISSUE TITLE
Make odl-solvers a namespace package?

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl-solvers#6]
As mentioned in [odl issue #19](https://github.com/odlgroup/odl/issues/19), we should make `odl-solvers` a namespace package under odl. Thus, imo, we should access solvers (with all its sub-packages) as `odl.solvers` in code. The documentation should also (somehow) be added to `odl`'s documentation, as to avoid fragmenting it.

**Comment by kohr-h** [comment]
Can't we do something similar for developers? What speaks against including them as Git submodules and making life easier for people who want to clone the code and work with it?

**Comment by adler-j** [comment]
Well, make a new `odl-core` library and move all current code there, then simply let `odl` have the others as submodules?

**Comment by kohr-h** [comment]
This has become a question rather than a TODO, see the discussion [here](https://github.com/odlgroup/odl/issues/20)
