### ISSUE TITLE
Newton's method 

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl-solvers#7]
I think we should have a Newton's method in this package. Right?

 I have a local implementation, including tests for it, that I can commit. Is use the CG method in this (`odl-solvers`) package to solve `f'(x)p = - f(x)`. It is probably not an optimal implementation, but I'm happy to receive feedback.

**Comment by adler-j** [comment]
What about [this](https://github.com/odlgroup/odl-solvers/blob/64d133fa91da17aeecc25b054bf1404f1ad75c09/odlsolv/iterative/iterative.py#L266)? Please submit a pull request and we can add yours aswell, but maybe you want to merge it?

Regarding using the CG method, I'd recommend allowing users to specify this somehow.

**Comment by aringh** [comment]
According to the wiki-article, when n=m this is indeed Newton's method. So maybe this is sufficient.

On the other hand, this method needs the user to define adjoints of the derivative. Moreover, in Newton's method a line search method is often useful (without it convergence is in general not guaranteed).

I will submit a pull request (in a little while), and you can have a look at it.

**Comment by aringh** [comment]
Related to what I guess we will talk about later today: where should it be placed? In which part of the package?

**Comment by adler-j** [comment]
Somewhere in solvers, depending on what it does exactly. I'm quite sure we will clean up solvers quite soon so anywhere should do.

**Comment by aringh** [comment]
Moved to odl, and solved by [this merge](https://github.com/odlgroup/odl/commit/ace54dfe7bd0dcf6f4a8bc058895bca14b8e5478)
